# Generated by Django 6.0.2 on 2026-02-20 11:53

import aqar.models
import cloudinary_storage.storage
import django.db.models.deletion
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نوع العقار (شقة/أرض)')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='المحافظة')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الخاصية (مثل: رخصة حفر)')),
                ('input_type', models.CharField(choices=[('text', 'نص عادي (Text)'), ('bool', 'نعم/لا (Switch)'), ('number', 'قيمة رقمية (Buttons + Input)')], default='bool', max_length=10, verbose_name='نوع الإدخال')),
                ('is_quick_filter', models.BooleanField(default=False, verbose_name='عرض في الفلتر السريع؟')),
                ('options_list', models.CharField(blank=True, max_length=200, null=True, verbose_name='الأرقام المقترحة')),
                ('icon', models.CharField(choices=[('CheckCircle2', '✔ علامة صح (افتراضي)'), ('ArrowUpFromLine', '🛗 أسانسير / مصعد'), ('Zap', '⚡ كهرباء / عداد'), ('Wind', '💨 غاز طبيعي'), ('Waves', '💧 مياه / سباحة'), ('Trees', '🌳 حديقة / لاندسكيب'), ('Car', '🚗 جراج / موقف'), ('Wifi', '📶 واي فاي / إنترنت'), ('ShieldCheck', '🛡 أمن وحراسة'), ('Snowflake', '❄ تكييف'), ('Tv', '📺 تلفزيون / دش'), ('Paintbucket', '🎨 تشطيب / ديكور'), ('Dumbbell', '💪 جيم / رياضة'), ('Utensils', '🍽 مطبخ'), ('BedDouble', '🛏 غرفة نوم'), ('Bath', '🛁 حمام')], default='CheckCircle2', max_length=50, verbose_name='شكل الأيقونة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_features', to='aqar.category')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='المدينة')),
                ('zone_label', models.CharField(default='حي', max_length=50, verbose_name='تسمية المنطقة الكبرى')),
                ('subdivision_label', models.CharField(default='مجاورة', max_length=50, verbose_name='تسمية المنطقة الصغرى')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqar.governorate')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('reference_code', models.CharField(default=aqar.models.generate_ref, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=15)),
                ('area_sqm', models.IntegerField(db_index=True)),
                ('description', models.TextField()),
                ('custom_map_image', models.ImageField(blank=True, null=True, upload_to='listings_maps/')),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('floor_number', models.IntegerField(blank=True, null=True)),
                ('building_number', models.CharField(blank=True, max_length=50, null=True)),
                ('apartment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('google_maps_url', models.URLField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('offer_type', models.CharField(choices=[('Sale', 'بيع'), ('Rent', 'إيجار')], db_index=True, default='Sale', max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'قيد المراجعة'), ('Available', 'متاح'), ('Sold', 'تم البيع')], db_index=True, default='Pending', max_length=20)),
                ('is_finance_eligible', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='listings_thumbnails/')),
                ('video', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='listings_videos/')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='رابط فيديو يوتيوب')),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='secure_docs/')),
                ('contract_image', models.ImageField(blank=True, null=True, upload_to='secure_docs/')),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('whatsapp_clicks', models.PositiveIntegerField(default=0, verbose_name='نقرات الواتساب')),
                ('call_clicks', models.PositiveIntegerField(default=0, verbose_name='نقرات الاتصال')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_listings', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqar.category')),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='governorate', chained_model_field='governorate', on_delete=django.db.models.deletion.CASCADE, to='aqar.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqar.governorate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('interaction_type', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqar.listing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('document_file', models.FileField(upload_to='secure_docs/')),
                ('document_type', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqar.listing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqar.feature')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_values', to='aqar.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings_photos/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='aqar.listing')),
            ],
        ),
        migrations.CreateModel(
            name='MajorZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqar.city')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='major_zone',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='city', chained_model_field='city', on_delete=django.db.models.deletion.CASCADE, to='aqar.majorzone'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_plan', models.ImageField(blank=True, null=True, upload_to='promotions/master_plans/')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('promo_type', models.CharField(choices=[('PROJECT', 'مشروع عقاري'), ('SERVICE', 'خدمة'), ('GENERAL', 'إعلان عام'), ('LISTING', 'إعلان VIP')], default='GENERAL', max_length=20)),
                ('developer_logo', models.ImageField(blank=True, null=True, upload_to='promotions/logos/')),
                ('cover_image', models.ImageField(upload_to='promotions/covers/')),
                ('video', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='promotions/videos/')),
                ('details_video', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='promotions/details_videos/')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='رابط فيديو يوتيوب')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('developer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_system', models.TextField(blank=True, null=True)),
                ('delivery_date', models.CharField(blank=True, max_length=50, null=True)),
                ('project_features', models.TextField(blank=True, null=True)),
                ('price_start_from', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('location_url', models.URLField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='عدد النقرات')),
                ('whatsapp_clicks', models.PositiveIntegerField(default=0, verbose_name='نقرات الواتساب')),
                ('call_clicks', models.PositiveIntegerField(default=0, verbose_name='نقرات الاتصال')),
                ('target_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='aqar.listing')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VIEW_LISTING', 'مشاهدة عقار'), ('VIEW_PROMO', 'مشاهدة إعلان'), ('CLICK_PROMO', 'ضغط على الإعلان'), ('CLICK_WHATSAPP', 'ضغط واتساب'), ('CLICK_CALL', 'ضغط اتصال'), ('SEARCH', 'بحث')], max_length=20, verbose_name='نوع الحدث')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP الزائر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التوقيت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aqar.listing', verbose_name='العقار')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aqar.promotion', verbose_name='الإعلان')),
            ],
            options={
                'verbose_name': 'سجل التحليلات',
                'verbose_name_plural': 'سجلات التحليلات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='promotions/gallery/')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='aqar.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(blank=True, max_length=100)),
                ('linked_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aqar.listing')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='aqar.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('major_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqar.majorzone')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='subdivision',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='major_zone', chained_model_field='major_zone', null=True, on_delete=django.db.models.deletion.CASCADE, to='aqar.subdivision'),
        ),
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_image', models.ImageField(upload_to='promotions/before/', verbose_name='صورة قبل')),
                ('after_image', models.ImageField(upload_to='promotions/after/', verbose_name='صورة بعد')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان (مثال: الريسبشن)')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformations', to='aqar.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_file', models.FileField(upload_to='master_plans/')),
                ('description', models.CharField(max_length=255)),
                ('major_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='aqar.majorzone')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='aqar.listing', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'مفضل',
                'verbose_name_plural': 'المفضلة',
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
