# Generated by Django 6.0.2 on 2026-02-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0002_promotionunit_image_promotionunit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان النصي'),
        ),
    ]
