# Generated by Django 6.0.2 on 2026-03-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0003_promotion_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الفون')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('plot_number', models.CharField(max_length=100, verbose_name='رقم القطعة')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='المجاورة')),
                ('district', models.CharField(max_length=100, verbose_name='الحي')),
                ('status', models.CharField(choices=[('Success', 'تم التنازل'), ('Pending', 'قيد الانتظار')], max_length=20, verbose_name='حالة التنازل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بحث عميل (ليد)',
                'verbose_name_plural': 'سجل بحث العملاء',
            },
        ),
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100, verbose_name='الحي')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='المجاورة')),
                ('plot_number', models.CharField(max_length=100, verbose_name='رقم القطعة')),
                ('procedure', models.CharField(max_length=255, verbose_name='الإجراء')),
                ('committee_number', models.CharField(max_length=100, verbose_name='رقم اللجنة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تنازل',
                'verbose_name_plural': 'التنازلات',
                'unique_together': {('district', 'neighborhood', 'plot_number')},
            },
        ),
    ]
