# Generated by Django 6.0.2 on 2026-03-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0004_waiverlead_waiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiver',
            name='procedure_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تاريخ الإجراء'),
        ),
    ]
