# Generated by Django 6.0.2 on 2026-03-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0005_waiver_procedure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Pending', 'قيد المراجعة'), ('Available', 'متاح'), ('Sold', 'تم البيع'), ('Rejected', 'مرفوض')], db_index=True, default='Pending', max_length=20),
        ),
    ]
