# Generated by Django 6.0.2 on 2026-07-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0006_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticslog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التوقيت'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='whatsapp_clicks',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='نقرات الواتساب'),
        ),
    ]
