# Generated by Django 6.0.2 on 2026-07-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0007_alter_analyticslog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='listings_photos/'),
        ),
    ]
