# Generated by Django 6.0.2 on 2026-07-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0008_alter_listingimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='listings_thumbnails/'),
        ),
    ]
