# Generated by Django 6.0.2 on 2026-07-24 00:09

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0009_alter_listing_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='contract_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='secure_docs/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='custom_map_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='listings_maps/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id_card_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='secure_docs/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='video',
            field=models.FileField(blank=True, max_length=500, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='listings_videos/'),
        ),
    ]
