# Generated by Django 6.0.2 on 2026-07-22 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aqar', '0007_alter_analyticslog_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_rooms', to=settings.AUTH_USER_MODEL, verbose_name='المشتري')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='aqar.listing', verbose_name='الإعلان')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_rooms', to=settings.AUTH_USER_MODEL, verbose_name='البائع')),
            ],
            options={
                'verbose_name': 'غرفة محادثة',
                'verbose_name_plural': 'غرف المحادثة',
                'ordering': ['-updated_at'],
                'unique_together': {('listing', 'buyer', 'seller')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوى الرسالة')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='تم الاستلام (صحين)')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة (صحين أزرق)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال (صح واحدة)')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='الغرفة')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['created_at'],
            },
        ),
    ]
