# Generated by Django 6.0.2 on 2026-02-20 11:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الرسالة')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('target_audience', models.CharField(choices=[('ALL', 'الكل'), ('Buyer', 'المشترين فقط'), ('Seller', 'الملاك/البائعين فقط'), ('Broker', 'السماسرة فقط')], default='ALL', max_length=20, verbose_name='الجمهور المستهدف')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('is_sent', models.BooleanField(default=False, editable=False, verbose_name='تم الإرسال؟')),
            ],
            options={
                'verbose_name': 'إرسال إشعار جماعي',
                'verbose_name_plural': '📣 إرسال إشعارات جماعية',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_phone', models.CharField(default='01000000000', max_length=20, verbose_name='رقم الاتصال')),
                ('whatsapp_number', models.CharField(default='20100000000', max_length=20, verbose_name='رقم الواتساب (بدون +)')),
            ],
            options={
                'verbose_name': 'إعدادات التواصل',
                'verbose_name_plural': 'إعدادات التواصل',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='المفتاح (كود الإعداد)')),
                ('value', models.CharField(max_length=500, verbose_name='القيمة')),
            ],
            options={
                'verbose_name': 'إعداد عام',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الهاتف')),
                ('whatsapp_link', models.CharField(blank=True, max_length=255, verbose_name='رابط الواتساب')),
                ('is_agent', models.BooleanField(default=False, verbose_name='هل هو موظف؟')),
                ('interests', models.TextField(blank=True, null=True, verbose_name='الاهتمامات')),
                ('client_type', models.CharField(choices=[('Buyer', 'مشترِي'), ('Seller', 'بائع'), ('Investor', 'مستثمر'), ('Marketer', 'مسوق')], db_index=True, default='Buyer', max_length=10, verbose_name='نوع العميل')),
                ('interested_in_rent', models.BooleanField(default=False, verbose_name='مهتم بالإيجار')),
                ('interested_in_buy', models.BooleanField(default=True, verbose_name='مهتم بالشراء')),
                ('fcm_token', models.TextField(blank=True, null=True, verbose_name='FCM Token')),
                ('is_owner', models.BooleanField(default=False, help_text='تفعيل هذا الخيار يمنع حذف هذا الحساب نهائياً حتى من قبل المديرين الآخرين.', verbose_name='مالك الموقع')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الإشعار')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='تمت القراءة؟')),
                ('notification_type', models.CharField(choices=[('System', 'إداري'), ('Listing', 'عقار'), ('Offer', 'عرض')], db_index=True, default='System', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
